apiVersion: v1
kind: Service
metadata: 
  name: mysql-svc
  namespace: mysql
  labels:
    app: mysql
spec:
  containers:
    - ports:
      containerPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8
          ports:
          - containerPort: 3306

          env:
            # Mysql Environment importing from Configmap
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_DATABASE
          
            # Mysql Environment importing from secret
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD

          # Container Volumes or storage
          volumesMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      # external volume or Storage
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim  
