apiVersion: v1
kind: Services
metadata: 
  name: mysql-svc
  namespace: mysql
  labels:
    app: mysql
spec:
  containers:
    - ports:
      containerPort: 3306
    selectors:
      labels:
        app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8
          ports:
          - containerPort: 3306
          # Mysql Environment
          env:
            - name: MYSQL_PASSWORD_ROOT
              value: password
          # Container Volumes or storage
          volumesMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      # external volume or Storage
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim  
