apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: nginx
spec:
  selector:
    app: nginx
  # for NodePort
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30007
